"""Rebuild the wallet seed file from current chain activity, by hand.

``app.workers.chain_tape`` now does this automatically every
``WALLET_DISCOVERY_INTERVAL_SECONDS`` and writes straight to the registry, so
this script is for the manual case: seeing the ranking before committing to
it, or regenerating ``config/fomo_wallets.json`` so the chosen wallets are
checked in rather than only living in the database.

Usage::

    .venv/bin/python scripts/discover_wallets.py --blocks 900 --top 20 [--dry-run]
"""

import argparse
import asyncio
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.chain.discovery import discover_wallets  # noqa: E402
from app.chain.tape import is_batch_too_large_error  # noqa: E402
from app.core.config import settings  # noqa: E402
from app.dex.chain import ChainClient  # noqa: E402
from app.dex.tokens import DexConfigError, resolve_pair  # noqa: E402

DEFAULT_FILE = ROOT / "config" / "fomo_wallets.json"


async def main(blocks: int, top: int, symbol: str, out: Path, write: bool) -> int:
    try:
        pair = resolve_pair(symbol)
    except DexConfigError as exc:
        print(f"unknown pair {symbol}: {exc}", file=sys.stderr)
        return 1

    client = ChainClient()
    try:
        await client.ensure_ready()
        print(f"scanning {symbol} over the last {blocks} blocks", flush=True)
        try:
            ranked = await discover_wallets(
                client, pair, blocks=blocks, top=top, chain_id=settings.rh_chain_id
            )
        except Exception as exc:
            if is_batch_too_large_error(exc):
                print(f"RPC refused a {blocks}-block range; retry with a smaller --blocks", file=sys.stderr)
                return 1
            raise

        if not ranked:
            print("no wallets classified in this window", file=sys.stderr)
            return 1

        print(f"\ntop {len(ranked)} wallets by traded volume:\n")
        for index, candidate in enumerate(ranked, start=1):
            print(f"{index:>3}. {candidate.address}  vol ${float(candidate.volume_usd):>12,.2f}  "
                  f"buys {candidate.buys:<3} sells {candidate.sells:<3} "
                  f"(bought ${float(candidate.bought_usd):,.0f} / sold ${float(candidate.sold_usd):,.0f})")

        if write:
            payload = {
                "_comment": [
                    "Wallets the chain tape watches -- no FOMO session required.",
                    f"Generated by scripts/discover_wallets.py from {symbol} activity,",
                    "ranked by traded volume, contracts excluded.",
                    "The worker also discovers wallets on its own schedule; this file",
                    "is the checked-in roster, useful for seeding a fresh database.",
                    "Add 'handle'/'display_name' by hand when you know who a wallet is.",
                ],
                "wallets": [
                    {
                        "address": candidate.address,
                        "note": f"{symbol}: vol ${float(candidate.volume_usd):,.0f}, "
                                f"{candidate.buys}B/{candidate.sells}S in discovery window",
                    }
                    for candidate in ranked
                ],
            }
            out.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n")
            print(f"\nwrote {len(ranked)} wallets to {out.relative_to(ROOT)}")
            print("next: make fomo-seed")
        return 0
    finally:
        await client.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--blocks", type=int, default=None)
    parser.add_argument("--top", type=int, default=None)
    parser.add_argument("--symbol", default=None, help="defaults to the first DEX_WATCH_SYMBOLS entry")
    parser.add_argument("--out", type=Path, default=DEFAULT_FILE)
    parser.add_argument("--dry-run", action="store_true", help="print the ranking without writing the seed file")
    args = parser.parse_args()
    chosen = args.symbol or (settings.dex_watch_symbols or "PONSUSDG").split(",")[0].strip()
    raise SystemExit(asyncio.run(main(
        args.blocks if args.blocks is not None else settings.wallet_discovery_blocks,
        args.top if args.top is not None else settings.wallet_discovery_top,
        chosen, args.out, not args.dry_run,
    )))
